### ISSUE TITLE
Rename to fluxible namespace

### ISSUE THREAD

**Issue by mridgway** [yahoo/flux-router-component#41]
This library has dependencies on some of the functionality that [fluxible-app](https://github.com/yahoo/fluxible-app) and [fluxible-plugin-routr](https://github.com/yahoo/fluxible-plugin-routr). It would make sense to namespace this similarly and call out the dependencies in the documentation instead of saying "this should have a router instance and an executeAction function".

It may also be worth exploring whether this should just be combined with fluxible-plugin-routr.

**Comment by cesarandreu** [comment]
+1

**Comment by redonkulus** [comment]
Looks like this can be closed now that fluxible-router is live. https://github.com/yahoo/fluxible-router
