### ISSUE TITLE
How to make navLink with query string?

### ISSUE THREAD

**Issue by mpipet** [yahoo/flux-router-component#49]
Hi,
I was wondering how to generate a navLink with queryString.
Example:
I d'like my href url looks like http://localhost:3000/en?query=string.

Even if i succeed making a such url, I don't really know how to handle this kind of data with flux-router

**Comment by gpbl** [comment]
> The makePath method does not handle query params at the moment. You can always tag on the query string yourself.

@lingyan What do you mean? Should I change they browser's history manually? I could not understand how to use querystrings :-(

**Comment by mpipet** [comment]
@gpbl  No need to change browser's history. 
The issue is to build a path like /categories/1/bottom-form/  and handle querystrings  like ?name=gpbl.

In flux router there is a difference between path and url,  url is composed of path and querystrings.

In my mind the best to handle url , is to build path with flux-router and querystrings separately with a node module like query-string.   Then you cancatenate and pass url to flux-router where it is needed, in the href prop in navLink object for example.

I hope, I answered your question.

**Comment by gpbl** [comment]
@mpipet  thanks for the answer. That's clear now. My problem then is using `NavLink`: when the user clicks a NavLink with query in `href`, the query is *not* added to the browser's history:

When the user clicks on this NavLink:
```xml
<NavLink href="/books?search=true">Enable search</NavLink>
```
my stores emit the change with a route containing the `query`, but the URL's history is not updated with `?search=true`.

```js
//example routes.js
routes: {
  books: { path: '/books' }
}
```

Not sure where to investigate the problem... I'm missing something in the routes config?

**Comment by gpbl** [comment]
Allright I got it, my store was using `currentRoute` instead of `route` for handling page changes. Phew. Sorry for bothering, :+1: for the immediate answer.
