### ISSUE TITLE
How to declare the default route

### ISSUE THREAD

**Issue by sAbakumoff** [yahoo/flux-router-component#53]
Howdy, 
I am using fluxible-app together with flux-router-plugin and historyWithHash util, here is the routes configuration:
```
[
    {
        name: 'home',
        method : 'get',
        path: '/',
        text: 'Home'
    },
    {
        name: 'customers',
        method : 'get',
        path: '/customers',
        text: 'Customers',
    }
]
```
and the initialization code in the client-side:
```
var app = new FluxibleApp({
	appComponent: React.createFactory(require('./components/MyApp.react'))
});

app.plug(routrPlugin({
	routes : require('./configs/routes')
}));


var context = app.createContext();

var AppComponent = app.getAppComponent();

var component = AppComponent({
	context: context.getComponentContext(),
	historyCreator: function historyCreator() {
	    return new HistoryWithHash({
	        useHashRoute: true
	    });
	},
	checkRouteOnPageLoad : true
});
React.render(component, document.getElementById('layout'));
```

This code is called from index.html page. I would like 'home' route to be loaded when index.html is opened, i.e. a user loads http://server/index.html. It does not work by default, the error "Url doesn't exist" error appears in the debug console.

I managed to fix it by using hash transform:
```
	        hashRouteTransformer: {
	            reverse : function (transformed) {
	                if (transformed === '')
	                    return '/';
	                return transformed;
	            }
	        }
```
But it seems to be so hackish that I doubt that it's the proper way to achieve my goal.
Could you please help me to figure out the way to do it right?

**Comment by lingyan** [comment]
@sAbakumoff   Did the fix help?

**Comment by sAbakumoff** [comment]
Hello,
Sorry for delayed reply.
Unfortunately the fix  does not help because the update to the most recent version of flux-router-component ain't working well.
I created the simple demo of what I am doing in my real application : https://github.com/sAbakumoff/Fluxible-SPA
As you can see it's very similar to routing sample : https://github.com/yahoo/flux-examples/tree/master/routing 
except of the routes are all hash-based
It works fine with flux-router-component ~0.4.x, but if I update the package to 0.5.4 then the following error appears on opening the application:
*unable to navigate to / cause : Error: Url does not exist*
Could you point to the breaking changes in version 0.5.4?
Thanks.

**Comment by lingyan** [comment]
Ah.  Two more changes needed to work with flux-router-component 0.5.x  (where we renamed navigate action payload field `path` to `url` to fix nomenclature):

1. upgrade fluxible-plugin-routr to ^0.3.0. 
2. https://github.com/sAbakumoff/Fluxible-SPA/blob/master/Scripts/app.js#L37  rename the key name `path` to `url`

Please try that out and let me know.  Thanks!

**Comment by sAbakumoff** [comment]
Thanks for reply.
I was able to upgrade to version 0.5.x of flux-router-component and checked the fix. Indeed it helps to solve the original problem and handles the deafult route. Unfortunately it's not enough in my application:
The main component needs to know the current page(route) when it renders itself:
https://github.com/sAbakumoff/Fluxible-SPA/blob/master/Scripts/components/SpaApp.react.js
but RouterMixin performs navigation in componentDidMount handler which seems to be too late.
This is why I still need the app to perform the navigation action before rendering the main component:
https://github.com/sAbakumoff/Fluxible-SPA/blob/master/Scripts/components/SpaApp.react.js
Of course it can check this.state.currentPage for null and render nothing in that case and update later, but it does not seem to be elegant solution to me..
Do you have any thoughts?

**Comment by lingyan** [comment]
@sAbakumoff It is actually the solution we would prefer.

In fact, this is exactly what we do on server side for our isomorphic apps: https://github.com/yahoo/flux-examples/blob/master/fluxible-router/server.js#L25 ;)

**Comment by sAbakumoff** [comment]
Thanks for reply, I changed my mind and use the approach of checking the state before rendering, like:
```
render: function() {
		var currentPage = this.state.currentPage;
		if(!currentPage){
			return(false);
		}
		var context = this.props.context;
		var component = React.createElement(currentPage.component, {context : context});
		return (
			<div id='wrapper'>
				<Menu currentPageName={this.state.currentPageName} pages={this.state.pages} context={context} />
				<div id='page-wrapper' key={this.state.currentPageName}>
					{component}
				</div>
			</div>
		);
  	}
```
The fix you made for the default route helped to solve the problem I faced originally, all works great for now.

**Comment by lingyan** [comment]
Cool.  I will close this issue then.  Thanks for using fluxible, and please keep letting us know your feedbacks!
