### ISSUE TITLE
scroll issue, undefined shows up in url

### ISSUE THREAD

**Issue by stanshillis** [yahoo/flux-router-component#56]
Upgraded from 0.4.5 to 0.5.1 and seeing a strange problem when scrolling. As soon as i scroll down on the page last part of the url in browser changes to "undefined". For example from .../login to .../undefined. Not using hash routing. Navigation seems to still work even with undefined in the url. If i disable the scrolling feature on router mixin then the issue goes away.

**Comment by lingyan** [comment]
@stanshillis  You can also try out latest version 0.5.2 (https://github.com/yahoo/flux-router-component/pull/58) to see if the problem goes away.

**Comment by stanshillis** [comment]
I will try to do it tomorrow and report back. Thank you.

**Comment by stanshillis** [comment]
The issue with "undefined" appears to be resolved; tried it with 0.5.3.

Something else came up though, i was using custom "type" value when triggering navigation through navigateAction, but when i set custom type then URL in the browser stops changing. It does move to that route and correct page is rendered, but it doesn't update url in browser's address bar.
I switched type value to "click" when triggering navigateAction and it is working fine then.

**Comment by stanshillis** [comment]
My use case was hypothetical where i was thinking of triggering navigation based on a schedule so i changed type. However i'm not actually doing that at the moment, but code with changed type was left behind accidentally. I found it when i upgraded to 0.5.3 because it caused regular user triggered navigation code to break :)

**Comment by lingyan** [comment]
I see. You can probably use the navParams to carry that information, instead of using navigation type.

I will close this issue now.  Feel free to open a new issue if you need help when adding that use case back.  Thanks for reporting this issue!
