### ISSUE TITLE
navigateAction doesn't update address bar

### ISSUE THREAD

**Issue by kilometers** [yahoo/flux-router-component#60]
I ran into the same question as #57, and likewise I decided that `navigateAction` was the right solution. While it works in the DOM redirecting to the home page after login, the address bar remains unchanged.

**Comment by lingyan** [comment]
Is it possible to share the sample code of how you execute navigateAction?

**Comment by kilometers** [comment]
It is run from another action, `login`:
```
'use strict';
var request = require('superagent');

var navigateAction = require('flux-router-component').navigateAction;

module.exports = function(context, payload, done){
	request.post('/auth/login')
	   .send(payload)
	   .end(function(res){
	     if (res.ok) {
	       context.executeAction(navigateAction, { url: '/' }, function(){});
	     } else {
	       alert('Error ' + res.text);
	     }
	   });
}
```

**Comment by kilometers** [comment]
Adding `type: 'click'` to the payload fixes it. Why? Looking over `navigate.js`, I don't see where `type` is used.

**Comment by lingyan** [comment]
Its used by RouterMixin: https://github.com/yahoo/flux-router-component/blob/master/lib/RouterMixin.js#L107

We should add a default type to allow programmatic navigation.

**Comment by lingyan** [comment]
@kilometers  Please upgrade to 0.5.4.  You can leave out the navigate type now.  It will use `default` as the type, and handled by RouterMixin the same way as `click`.

**Comment by lingyan** [comment]
@kilometers I am closing this issue.  Feel free to re-open if you need to.
