### ISSUE TITLE
Don't trigger navigate action on mailto:

### ISSUE THREAD

**Issue by imbrianj** [yahoo/flux-router-component#62]
Akin to a hash URL, probably don't want to trigger an action for a mailto: link.

https://github.com/yahoo/flux-router-component/blob/master/lib/NavLink.js#L24

**Comment by lingyan** [comment]
Can you simply not use `NavLink` component for mailto: links?  Just use plain `<a>` instead.

**Comment by imbrianj** [comment]
If delegated, it'd require some hackiness.  If we know that a flux route should never trigger an action for mailto: seems like a good candidate for including in the base - such as hash URLs.

The use-case for mailto: in general is rather uncompelling so feel free to ignore.  In our current setup, I was adding one as FPO and realized it wouldn't work.

**Comment by lingyan** [comment]
In general, we recommend to not use NavLink if the link is not meant to trigger a client side navigation.  Closing this issue.  Thanks!
