### ISSUE TITLE
Context is required as prop

### ISSUE THREAD

**Issue by gpbl** [yahoo/flux-router-component#65]
Thanks for the last update, passing the context to React helps a lot to clean up the code.
I still receive React warnings about a missing context prop, because of this [PropType](https://github.com/yahoo/flux-router-component/blob/master/lib/NavLink.js#L21). Shouldn't it be skipped?

**Comment by lingyan** [comment]
Good catch. Removing isRequird will fix the warning. I will fix it. Thanks!
