### ISSUE TITLE
Documentation example links are broken

### ISSUE THREAD

**Issue by optilude** [yahoo/flux-router-component#68]
It's pretty hard to figure out how to use this on its own. There is no real explanation of how to supply an `executeAction()` or a `makePath()` in a non-fluxible flux app. 

he example link from the README is broken and I haven't been able to find it. I suspect fixing this would help.

**Comment by lingyan** [comment]
The flux example app was renamed from `routing` to `fluxible-router`.  Updated the links: https://github.com/yahoo/flux-router-component/blob/master/examples/simple-flux.md

Thanks for reporting.

**Comment by optilude** [comment]
I may be missing something, but that example doesn't seem to be using flux-router-component at all. It seems to be using a fluxible plugin, and doesn't explain how to implement e.g. executeAction() for your own method.

**Comment by lingyan** [comment]
It uses RouterMixin and NavLink:
https://github.com/yahoo/flux-examples/blob/master/fluxible-router/components/Application.jsx#L13
https://github.com/yahoo/flux-examples/blob/master/fluxible-router/components/Nav.jsx

Fluxible router plugin is used to add routing related functions to component Context:
https://github.com/yahoo/flux-examples/blob/master/fluxible-router/app.js#L8

There is a tutorial talking about routing with flux-router-component: http://www.fluxible.io/tutorials/routing.html  It is not perfect, some of it is outdated.  We are fixing the tutorial very soon.  Hopefully it can help you a bit to understand what pieces are needed and how they fit together.
