### ISSUE TITLE
Question: Webpack is not recompiling when JSX file is changed

### ISSUE THREAD

**Issue by edisonthk** [yahoo/flux-router-component#72]
### Question
I wonder why webpack is not watching the jsx file. I run `npm run dev` and tried to change app/components/Html.jsx file and there is nothing changed in my app/components/statics/build/bundle.js which is output file of reactjs. 

However, when I changed port from 3000 to 3040 in server.js and nodemon is working and restart it. I wonder if there is any conflict between webpack watch and nodemon watch.

### My problem repo
https://github.com/edisonthk/fluxible-router-playground

### Results I got
```
Edisonthks-MacBook-Air:codegarage edisonthk$ npm run dev

> codegarage@0.0.0 dev /Users/edisonthk/Documents/Vagrantfile/Flux/codegarage
> nodemon --ignore app/statics/build/ -e js server & ./node_modules/.bin/webpack --watch --debug

10 Feb 19:44:16 - [nodemon] v1.3.6
10 Feb 19:44:16 - [nodemon] to restart at any time, enter `rs`
10 Feb 19:44:16 - [nodemon] watching: *.*
10 Feb 19:44:16 - [nodemon] starting `node server server.js`
Listening on port 3000
Hash: 5960085e6dcfaa96f19d
Version: webpack 1.5.3
Time: 1362ms
    Asset    Size  Chunks             Chunk Names
bundle.js  774761       0  [emitted]  main
   [0] ./app/client.js 914 {0} [built]
   [1] ./app/app.js 647 {0} [built]
   [4] ./app/routes.js 987 {0} [built]
   [5] ./app/stores/ApplicationStore.js 1926 {0} [built]
   [6] ./app/stores/TimeStore.js 854 {0} [built]
   [7] ./app/stores/PageStore.js 841 {0} [built]
 [112] ./app/actions/updateTime.js 254 {0} [built]
    + 191 hidden modules
10 Feb 19:45:04 - [nodemon] restarting due to changes...
10 Feb 19:45:04 - [nodemon] starting `node server server.js`
Listening on port 3040

```

I have moving all of my developmnet file from root to app to make my developing easier. If there is anything wrong with my configuration such as webpack.config, package.json, etc. Please let me know.

**Comment by lingyan** [comment]
Html.jsx is only used on server side, so it will not be webpacked into bundle.js.  Did you try changing other jsx files?

I am not sure what difference port 3000 and 3040 makes.  Did you have anything else running on port 3000?

We used to do similar thing as you did using `nodemon & webpack`, and later switched to grunt-concurrent for managing concurrent nodemon and webpack: https://github.com/yahoo/flux-examples/blob/master/Gruntfile.js

**Comment by edisonthk** [comment]
Oh! I tried to change Page.jsx and Application.jsx and it works. It might sounds weird that only Html.jsx is not working. And here's the results in terminal.

```
Edisonthks-MacBook-Air:codegarage edisonthk$ npm run dev

> codegarage@0.0.0 dev /Users/edisonthk/Documents/Vagrantfile/Flux/codegarage
> nodemon --ignore app/statics/build/ -e js server & ./node_modules/.bin/webpack --watch --debug

11 Feb 02:37:06 - [nodemon] v1.3.6
11 Feb 02:37:06 - [nodemon] to restart at any time, enter `rs`
11 Feb 02:37:06 - [nodemon] watching: *.*
11 Feb 02:37:06 - [nodemon] starting `node server server.js`
Listening on port 3000
Hash: e27800d049e94eeacc5f
Version: webpack 1.5.3
Time: 223ms
    Asset    Size  Chunks             Chunk Names
bundle.js  774736       0  [emitted]  main
    + 198 hidden modules
Hash: eb4f2bf0cad99b1680e1
Version: webpack 1.5.3
Time: 143ms
    Asset    Size  Chunks             Chunk Names
bundle.js  744143       0  [emitted]  main
    + 184 hidden modules
Hash: e27800d049e94eeacc5f
Version: webpack 1.5.3
Time: 176ms
    Asset    Size  Chunks             Chunk Names
bundle.js  774736       0  [emitted]  main
  [54] ./app/actions/updateTime.js 254 {0} [built]
    + 197 hidden modules
Hash: c12f4221276f727a0c21
Version: webpack 1.5.3
Time: 131ms
    Asset    Size  Chunks             Chunk Names
bundle.js  774748       0  [emitted]  main
    + 198 hidden modules
```

I change 3000 to 3040 just for experiment either nodemon watch is working or not and nodemon watch is working well. 

So, the problems is only Html.jsx isn't watched if it is changed. I will try grunt-concurrent to see either it will solve this problem. Thank you for your cooperation.

**Comment by lingyan** [comment]
To make nodemon work with Html.jsx, you just need to configure it to watch .jsx files as well.  Here is how we do it in Gruntfile: https://github.com/yahoo/flux-examples/blob/master/Gruntfile.js#L30  You can also configure nodemon to watch non .js files, even if you don't use grunt: https://github.com/remy/nodemon#running-non-node-scripts

Closing this issue.
