### ISSUE TITLE
React v0.13.0 Beta support?

### ISSUE THREAD

**Issue by edword** [yahoo/flux-router-component#73]
This might be a stretch, but any chance 0.13 support will be rolling in soon?

Thx!!!

**Comment by edword** [comment]
In the event it's helpful, it looks like all tests are passing w/ 0.13 beta (https://github.com/edword/flux-router-component). Thanks!

**Comment by jedireza** [comment]
Could you share a link to the passing tests?

**Comment by edword** [comment]
Sure thing : https://travis-ci.org/edword/flux-router-component

**Comment by lingyan** [comment]
@edword 0.5.10 released: https://github.com/yahoo/flux-router-component/releases/tag/v0.5.10 

Please give it a try.  Thanks!

**Comment by edword** [comment]
AWESOME, thx! :sparkles:
