### ISSUE TITLE
Remembering scroll position broken in Firefox

### ISSUE THREAD

**Issue by Legogris** [yahoo/flux-router-component#75]
Broken in Firefox 35.0.1 by e2d52d6fa8374094aa77d5d3a5c9331f566539f6. Using the old code causes no problems.
It works in Chromium though - seems like the handling of apply for undefined values are different?

**Comment by lingyan** [comment]
@Legogris Thanks for reporting!  Fixed in 0.5.11: https://github.com/yahoo/flux-router-component/releases/tag/v0.5.11
