### ISSUE TITLE
Please update React.js dependency.

### ISSUE THREAD

**Issue by sAbakumoff** [yahoo/flux-router-component#77]
React.js 0.13.0-rc1 is out and it's time to try it out!
However, "flux-router-component@0.5.11 wants react@>=0.12.0 <=0.13.0-beta.x" : 
 "peerDependencies": {
    "react": ">=0.12.0 <=0.13.0-beta.x"
  }
Could you please update it?

**Comment by lingyan** [comment]
@sAbakumoff  Please try latest 0.5.12 release: https://github.com/yahoo/flux-router-component/releases/tag/v0.5.12

**Comment by sAbakumoff** [comment]
Thank you! I think fluxible also needs to be updated: https://github.com/yahoo/fluxible/blob/master/package.json
shall I enter the new issue in fluxible repo?

**Comment by lingyan** [comment]
@sAbakumoff Done: https://github.com/yahoo/fluxible/releases/tag/v0.2.4
