### ISSUE TITLE
Should be a navigation type for replaceState

### ISSUE THREAD

**Issue by tastywheat** [yahoo/flux-router-component#82]
Could you add replaceState to the click type options? 

```
switch (navType) {
            case TYPE_CLICK:
            case TYPE_DEFAULT:
                historyState = {params: (nav.params || {})};
                if (this._enableScroll) {
                    window.scrollTo(0, 0);
                    historyState.scroll = {x: 0, y: 0};
                    debug('on click navigation, reset scroll position to (0, 0)');
                }
                pageTitle = nav.params && nav.params.pageTitle || null;
                this._history.pushState(historyState, pageTitle, newState.route.url);
                break;
            case TYPE_POPSTATE:
                if (this._enableScroll) {
                    historyState = (this._history.getState && this._history.getState()) || {};
                    var scroll = (historyState && historyState.scroll) || {};
                    debug('on popstate navigation, restore scroll position to ', scroll);
                    window.scrollTo(scroll.x || 0, scroll.y || 0);
                }
                break;
        }
```

**Comment by lingyan** [comment]
@tastywheat  Do you mean allow using replaceState(), for `this._history.pushState(historyState, pageTitle, newState.route.url);`?

**Comment by ross-pfahler** [comment]
I'm not sure if this exactly makes sense, but replaceState may be used in an endless scroll situation to preserve some sort of bookmarking / sharing url capability.

I could see it being used without reseting scroll position -- which would lead me to believe it is a different navType. 

@tastywheat's what is your use case?

**Comment by tbo** [comment]
@ross-pfahler I have pretty much the same problem: I need to implement the size selection on a mobile e-commerce site. Each product size should be accessible by external product search engines. But it would be quite irritating for a user if the viewport changes each time an option has been changed (especially on an mobile site). And - as you already stated - it would also be useful for endless scrolling.

I would propose something like this: #91

**Comment by lingyan** [comment]
Addressed by https://github.com/yahoo/flux-router-component/pull/91.  Supported starting from https://github.com/yahoo/flux-router-component/releases/tag/v0.6.2.

**Comment by ross-pfahler** [comment]
thanks for following up @lingyan!

**Comment by lingyan** [comment]
No problem.  Thanks for everyone's input and contribution: @ross-pfahler @tbo
