### ISSUE TITLE
/undefined when scrolling in IE11

### ISSUE THREAD

**Issue by gpbl** [yahoo/flux-router-component#86]
(This should be different from #56). When scrolling in IE11, i see `/undefined` in the URL – you can reproduce it with the example app, resizing the window so that you can scroll down.
It seems because RouterMixin [calls](https://github.com/yahoo/flux-router-component/blob/master/lib/RouterMixin.js#L30) `pushState` without enough arguments.

**Comment by lingyan** [comment]
@gpbl Thanks for reporting!  Fixed in 0.6.1 release: https://github.com/yahoo/flux-router-component/releases/tag/v0.6.1
