### ISSUE TITLE
On Internet Explorer, RouterMixin's "Scroll Position Management" is setting the url path to "undefined"

### ISSUE THREAD

**Issue by phaddius** [yahoo/flux-router-component#93]
When RouterMixin's enableScroll is not set to false, something is happening to cause the url path to get set to undefined.  For example, if I go to www.example.com/?query1=true&query2=false, and then I scroll down any amount, the url gets replaced with www.example.com/undefined.  Something is not playing well with IE's history management I think.  It works fine on Chrome, Firefox, Safari.  It's just IE (more specifically IE11, via VMWare on Mac, Windows 7 and 8).

The temporary fix is just to disable it by passing {enableScroll : false} when initializing the component with the RouterMixin

**Comment by lingyan** [comment]
@phaddius  Hmm.  Are you using 0.6.1?  We fixed this issue in that release, with PR https://github.com/yahoo/flux-router-component/pull/88

**Comment by phaddius** [comment]
I'm on 0.6.0, I'll try out the latest, thanks!

**Comment by lingyan** [comment]
Cool.
