### ISSUE TITLE
Add className to NavLink component

### ISSUE THREAD

**Issue by mwelche** [yahoo/flux-router-component#96]
I'm trying to style the NavLink components with classes (not inline styles) but className doesnt seem to work.

```
<NavLink className='nav__link--primary u-block' href='/products'>Products</NavLink>
```

**Comment by lingyan** [comment]
@mwelche Thanks for reporting.  Just want to double check with you.  Are you using fluxible-router?  I just tried NavLink from flux-router-component, it works fine.

There was a PR in fluxible-router that fixed this: https://github.com/yahoo/fluxible-router/pull/7  It was merged, probably just not released.  I will check it out.  Thanks!

**Comment by mwelche** [comment]
@lingyan you're right, I am using fluxible-router. I'll keep an eye out until the npm package is updated with the fix. Thanks!

**Comment by lingyan** [comment]
@jedireza Could you please let @mwelche know after you get the fix into fluxible-router and released today?  Thanks!

**Comment by jedireza** [comment]
[`fluxible-router@0.1.1`](https://www.npmjs.com/package/fluxible-router) has been published

**Comment by mwelche** [comment]
thanks guys!
